# Generated by Django 2.2.5 on 2019-11-21 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_historico'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ativos',
        ),
        migrations.DeleteModel(
            name='Atual',
        ),
        migrations.RemoveField(
            model_name='historico',
            name='close',
        ),
        migrations.RemoveField(
            model_name='historico',
            name='date',
        ),
        migrations.RemoveField(
            model_name='historico',
            name='high',
        ),
        migrations.RemoveField(
            model_name='historico',
            name='low',
        ),
        migrations.RemoveField(
            model_name='historico',
            name='open',
        ),
        migrations.RemoveField(
            model_name='historico',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='historico',
            name='volume',
        ),
    ]
