# Generated by Django 2.2.5 on 2019-11-21 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191121_0635'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Historico',
        ),
    ]
